// Sample Kyoto rest spots for seeding
export const sampleSpots = [
  {
    title: "鴨川・丸太町ベンチ",
    description: "丸太町橋のたもとにある、柳の木陰のベンチ。川面の光がゆれて、風が頬をなでる。仕事のことを忘れて、ただ水を見ていられる場所。",
    latitude: 35.0186,
    longitude: 135.7700,
    walking_minutes: 3,
    tags: ["川沿い", "ベンチあり", "静か", "5分休憩向き"],
    rest_duration_minutes: 5,
    rest_cue: "水の音を聞く",
    photo_url: "/spots/kamogawa-marutamachi.jpg",
  },
  {
    title: "下鴨神社・糺の森入口",
    description: "原生林が残る糺の森。木漏れ日が揺れる参道を少し歩くだけで、空気がやわらかく変わる。鳥の声だけが聞こえる。",
    latitude: 35.0382,
    longitude: 135.7724,
    walking_minutes: 8,
    tags: ["緑が多い", "静か", "人が少ない", "10分休憩向き"],
    rest_duration_minutes: 10,
    rest_cue: "空を10秒見る",
    photo_url: "/spots/tadasu-no-mori.jpg",
  },
  {
    title: "高瀬川・木屋町の路地",
    description: "細い高瀬川沿いの路地。水が静かに流れ、朝の光が石畳を照らす。人通りが少ない午前中がおすすめ。",
    latitude: 35.0050,
    longitude: 135.7710,
    walking_minutes: 5,
    tags: ["川沿い", "静か", "人が少ない", "5分休憩向き"],
    rest_duration_minutes: 5,
    rest_cue: "深呼吸を3回する",
    photo_url: "/spots/takasegawa.jpg",
  },
  {
    title: "御所・出水の小道",
    description: "京都御所の西側、出水口から入る小さな砂利道。広い空と古い松の木。ベンチに座って空を見上げると、思考が静かになる。",
    latitude: 35.0230,
    longitude: 135.7620,
    walking_minutes: 7,
    tags: ["緑が多い", "ベンチあり", "静か", "一人向き", "10分休憩向き"],
    rest_duration_minutes: 10,
    rest_cue: "空を10秒見る",
    photo_url: "/spots/gosho-demizu.jpg",
  },
  {
    title: "白川・知恩院前の柳並木",
    description: "白川に沿って柳が揺れる静かな小道。石橋の上に立つと、水のせせらぎと柳の葉音だけの世界。",
    latitude: 35.0050,
    longitude: 135.7810,
    walking_minutes: 6,
    tags: ["川沿い", "緑が多い", "静か", "5分休憩向き"],
    rest_duration_minutes: 5,
    rest_cue: "水の音を聞く",
    photo_url: "/spots/shirakawa.jpg",
  },
  {
    title: "哲学の道・法然院手前",
    description: "哲学の道の北端近く、法然院の手前の静かな区間。桜の木が並び、疏水の水が穏やかに流れる。特に平日の午前は人がほとんどいない。",
    latitude: 35.0270,
    longitude: 135.7960,
    walking_minutes: 10,
    tags: ["川沿い", "緑が多い", "人が少ない", "一人向き", "10分休憩向き"],
    rest_duration_minutes: 10,
    rest_cue: "スマホを30秒伏せる",
    photo_url: "/spots/tetsugaku.jpg",
  },
  {
    title: "建仁寺・裏庭の縁側",
    description: "建仁寺の裏手、人があまり来ない小さな庭。苔と石と静寂。座って庭を眺めるだけで、頭の中が少し整理される。",
    latitude: 34.9990,
    longitude: 135.7740,
    walking_minutes: 5,
    tags: ["静か", "人が少ない", "一人向き", "5分休憩向き"],
    rest_duration_minutes: 5,
    rest_cue: "深呼吸を3回する",
    photo_url: "/spots/kennin-ji.jpg",
  },
  {
    title: "船岡山公園・頂上ベンチ",
    description: "小さな丘の頂上から京都市街が一望できる。風が気持ちよく、空が広い。登りは3分。短い散歩と展望で気分転換。",
    latitude: 35.0420,
    longitude: 135.7470,
    walking_minutes: 8,
    tags: ["緑が多い", "ベンチあり", "人が少ない", "10分休憩向き"],
    rest_duration_minutes: 10,
    rest_cue: "空を10秒見る",
    photo_url: "/spots/funaokayama.jpg",
  },
  {
    title: "鴨川デルタ・出町柳",
    description: "賀茂川と高野川が合流するデルタ地帯。飛び石に座って足を川に向ける。水のきらめきを見ているだけで5分が過ぎる。",
    latitude: 35.0310,
    longitude: 135.7730,
    walking_minutes: 4,
    tags: ["川沿い", "ベンチあり", "5分休憩向き"],
    rest_duration_minutes: 5,
    rest_cue: "水の音を聞く",
    photo_url: "/spots/kamogawa-delta.jpg",
  },
  {
    title: "梅小路公園・芝生の隅",
    description: "広い芝生の端に座って、空を見上げる。新幹線の音が遠くに聞こえるけれど、それもやがて風景に溶ける。",
    latitude: 34.9870,
    longitude: 135.7520,
    walking_minutes: 7,
    tags: ["緑が多い", "ベンチあり", "静か", "10分休憩向き"],
    rest_duration_minutes: 10,
    rest_cue: "空を10秒見る",
    photo_url: "/spots/umekoji.jpg",
  },
];
